service: example-serverless

frameworkVersion: '3'

plugins:
  - ../carbonless.js

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events: # All events associated with this function
      - httpApi: 'GET /'
